### ISSUE TITLE
Using a CSS preprocessor instead of raw CSS?

### ISSUE THREAD

**Issue by roshbhatia** [GMertz/BookieClicker#1]
Hi Gabe,

Just stumbled across your repo and saw you were using a regular ol' .css file for styling. I'd like to suggest maybe using a css preprocessor like SASS (https://sass-lang.com/) as it'll help this become more maintainable over time.

Additionally, is there any documentation on how to get this up and running? I'd like to try it out myself if possible.

**Comment by GMertz** [comment]
Hey Roshan thanks for the comment!

I went ahead and added in a readme which details how to get Bookie Clicker up and running on your machine.

As far as using a CSS pre-processor goes, because the project is fairly narrow in scope, and because I likely wont be updating it any further, I didn't see the need to use anything beyond basic CSS, but thank you for the suggestion/resource!
